name: "Updated hello.txt"
on:
  # Update the file on push so cron job doesn't run endlessly.
  push:
    branches:
      - main
  # schedule:
  # # Run every five minutes
  # - cron: "*/5 * * * *"

jobs:
  update_hello_file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm run start 
    - run: |
        git config --global user.name "Cron Bot"
        git config --global user.email "hello@dennisokeeffe.com"

        git add -A
        git commit -m "chore: Updated hello.txt"
        git push